apps: Update Falco to v0.38.2
Falco-exporter chart updated to v0.12.1 (no change in app version)

PSP mount path prefixes were adjusted to primarily to Make It Work.

From the CHANGELOG:

> Note that, the /sys/module/falco is now mounted as /sys/module since
> we do not know which kind of driver will be used. The falco folder
> exists under /sys/module only when the kernel module is loaded, hence
> it’s not possible to use the /sys/module/falco hostpath when
> driver.kind is set to auto.

Use plural variant of falco rules setting to fix

> Using deprecated config key 'rules_file' (singular form). Please use new 'rules_files' config key (plural form).
> Error: Error reading config file (/etc/falco/falco.yaml): both 'rules_files' and 'rules_file' keys set