docs: Fix config schema
It seems like jsonschema2md ironically doesn't validate the schema of the input
it receives. :)

It fails horribly with:

```
file:///home/cklein/elastisys/welkin/node_modules/@adobe/jsonschema2md/lib/markdownBuilder.js:697
        ...schema[keyword`examples`].map((example) => paragraph(code('yaml', yaml.dump(example, undefined, 2)))),
                                     ^

TypeError: schema[keyword].map is not a function or its return value is not iterable
    at makeexamples (file:///home/cklein/elastisys/welkin/node_modules/@adobe/jsonschema2md/lib/markdownBuilder.js:697:38)
    at file:///home/cklein/elastisys/welkin/node_modules/@adobe/jsonschema2md/lib/markdownBuilder.js:762:14
    at Array.map (<anonymous>)
    at makeproplist (file:///home/cklein/elastisys/welkin/node_modules/@adobe/jsonschema2md/lib/markdownBuilder.js:750:54)
    at file:///home/cklein/elastisys/welkin/node_modules/@adobe/jsonschema2md/lib/markdownBuilder.js:831:16
    at Array.map (<anonymous>)
    at makedefinitions (file:///home/cklein/elastisys/welkin/node_modules/@adobe/jsonschema2md/lib/markdownBuilder.js:818:10)
    at file:///home/cklein/elastisys/welkin/node_modules/@adobe/jsonschema2md/lib/markdownBuilder.js:888:10
    at /home/cklein/elastisys/welkin/node_modules/ferrum/src/sequence.js:1234:12
    at /home/cklein/elastisys/welkin/node_modules/ferrum/src/sequence.js:807:5
```

I added `console.log(schema[keyword`examples`]);` before the failing line and,
long story short, it seems like jsonschema2md expects a list of examples and not
a string.