fix: update yq4 syntax in explain.bash
It is not clear what version introduced this change,
but it appears in the yq DSL, "join" and "split"
are now expected to be called as functions: join(".")

They simply stopped working as infix operators: join "."

Without this change, all calls to explain.bash fail
with the error message:

> Error: cannot join with !!str, can only join arrays of scalars